//Configuration for YTPlayer
//Automatically Generated by PhantomBot at Startup
//Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25003;
var channelName = "pb_test";
var auth="IbiVDDowlGNic2YYCyxtHU9aLmbAAw";
var http="http://";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
function getProtocol() { return http; }
